### ISSUE TITLE
`Ctrl+q` does not prevent autosaving!

### ISSUE THREAD

**Issue by javadr** [ferzapata/gedit-autosave#3]
Thank you once again for your excellent work. 

In the latest update, you've implemented actions to prevent autosaving. However when the user presses `Ctrl+q` or clicks the close button on the window, `gedit` prompts for saving a new file, and autosaving becomes unnecessary.

I'm considering redefining the `on_key_press` function to absorb the `Ctrl+q` combination. Do you have any alternative suggestions or considerations regarding this approach?"

**Comment by fernzi** [comment]
The application probably has a quit action, or some sort of shutdown event. I wouldn't do this sort of thing through key presses, cause I imagine they can be rebound, or set to different keys on other languages (or just bypassed by pressing the × button on the window).

**Comment by javadr** [comment]
I have checked all of its actions, and there is no quit action!
Check the list below:

 'bookmark-next'
 'bookmark-prev'
 'bookmark-toggle'
 'bottom-panel'
 'check-spell'
 'clear-highlight'
 'close'
 'close-all'
 'comment'
 'config-spell'
 'copy'
 'cut'
 'delete'
 'docinfo'
 'find'
 'find-next'
 'find-prev'
 'focus-active-view'
 'fullscreen'
 'goto-line'
 'hamburger-menu'
 'highlight-mode'
 'inline-spell-checker'
 'leave-fullscreen'
 'managedsession'
 'move-to-new-window'
 'multiedit'
 'new-tab'
 'new-tab-group'
 'next-document'
 'next-tab-group'
 'open'
 'overwrite-mode'
 'paste'
 'previous-document'
 'previous-tab-group'
 'print'
'quickopen'
 'quran'
 'redo'
 'reopen-closed-tab'
 'replace'
 'revert'
 'save'
 'save-all'
 'save-as'
 'savesession'
 'select-all'
 'session_0'
 'side-panel'
 'sort'
 'text-larger'
 'text-normal'
 'text-smaller'
 'time'
 'uncomment'
 'undo'

**Comment by fernzi** [comment]
It might be on the GtkApplication rather than on the window. Can probably use the Gtk inspector to be sure.

**Comment by javadr** [comment]
Unfortunately, I didn't find anything. Could you help me with this issue?

**Comment by fernzi** [comment]
I think 05cf5d394684eec6eb8fa650148d26d56bd7a8da should've fixed this. It shouldn't autosave on Gedit's own dialogs anymore. See if that behaves like you expect.
